### ISSUE TITLE
Calibration Tools not working with latest Autoware

### ISSUE THREAD

**Issue by dtonda8** [dtonda8/CalibrationTools#1]
`rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO` output:

![image](https://github.com/user-attachments/assets/c9aef73a-703d-4925-b43c-a9af3698cce5)

`colcon build` attempt [here](https://github.com/tier4/CalibrationTools/issues/169#issuecomment-2292238295) by @TimDing-aoi

This is most likely due to this fork using incorrect package naming.

**Comment by dtonda8** [comment]
This issue seems to be resolved with the [latest push](https://github.com/dtonda8/CalibrationTools/commit/9fa5125faa7888692f0be0fde735639e1ba40ddd). I managed to successfully `colcon build` calibration tools with the latest autoware.  Ensure `rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO` does not have any errors before building. @TimDing-aoi If you're still facing issues relating to this fork, please add a full screenshot of the error (or create a new issue).

**Comment by subramanians1** [comment]
Hi i tried was trying to build with autoware release v2024.11 customized for my own test vehicle and faced the following errors:
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
extrinsic_reflector_based_calibrator: Cannot locate rosdep definition for [kalman_filter]
extrinsic_mapping_based_calibrator: Cannot locate rosdep definition for [kalman_filter]
extrinsic_ground_plane_calibrator: Cannot locate rosdep definition for [kalman_filter]
extrinsic_lidar_to_lidar_2d_calibrator: Cannot locate rosdep definition for [kalman_filter]

**Comment by dtonda8** [comment]
This seems to be a naming error. I believe `kalman_filter` was renamed to `autoware_kalman_filter` in the latest Autoware versions. If you want to continue using this fork, try:
- renaming all the times "kalman_filter" is used to "autoware_kalman_filter" in the `package.xml` files [here](https://github.com/search?q=repo%3Adtonda8%2FCalibrationTools%20%3Ekalman_filter%3C&type=code)
- Update imports to correct naming [here](https://github.com/search?q=repo%3Adtonda8%2FCalibrationTools+%3Ckalman_filter&type=code)
- Ensure the package is accessed correctly for remaining instances [here](https://github.com/search?q=repo%3Adtonda8%2FCalibrationTools+kalman_filter&type=code). They use something like `autoware::kalman_filter` for the latest versions, [e.g.](https://github.com/search?q=repo%3Aautowarefoundation%2Fautoware.core+autoware%3A%3Akalman_filter&type=code)

This is a bit tricky, so you could also try the latest version of the original CalibrationTools

**Comment by subramanians1** [comment]
I tried witht the new CalibrationTools. But couldnt still find the latest documentation to use it.
